### ISSUE TITLE
"Fix" Issue Dashboard

### ISSUE THREAD

**Issue by Meisolsson** [github/android#678]
Don't know if it was ever implemented but we should take a look at it.

**Comment by fadils** [comment]
Could you please elaborate more.

**Comment by Meisolsson** [comment]
Well, it  nothing loads, mentioned is empty and created is empty. I looked at it and looks like it should work but nothing loads.

**Comment by fadils** [comment]
Mmhh.. the point of confusion is because it works on my end.

![screenshot_2015-01-15-15-19-28](https://cloud.githubusercontent.com/assets/6204776/5754395/c7b688c4-9cca-11e4-9908-de536ddd5bf2.png)

![screenshot_2015-01-15-15-26-12](https://cloud.githubusercontent.com/assets/6204776/5754447/9370440a-9ccb-11e4-85f2-e3ad62ee2604.png)

**Comment by Meisolsson** [comment]
Oh, cause I even tried to remove the filter an i still got nothing :confused:

**Comment by fadils** [comment]
It seems to this is a dupe of #312

=(

Sorry @Meisolsson. From the GitHub API page, we cannot see issues created in the repo we're not a member of.

**Comment by Meisolsson** [comment]
Okey, thought you could see all your issues. Just me not knowing how it works

**Comment by fadils** [comment]
Some updates regarding this. Please refer to #312.

I will close this one.
